{
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "SubirCambiosOffline"
	},
	"OnSuccess": "/LigaArgentinaFutbol/Actions/Offline/LimpiarStorage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Guardando cambios...",
	"Service": "/LigaArgentinaFutbol/Services/FUTBOL.service"
}